protospace:
  user_name: 'yuki121010'
  Access_Key_Id: 'AKIAJEE7E2WNAGMODATQ'
  Secret_Access_Key: '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'
  Password: 'qdyl2It5egYG'
  Direct_Signin_Link: 'https://037075010000.signin.aws.amazon.com/console'
